require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SignupsController do

  def mock_signup(stubs={})
    @mock_signup ||= mock_model(Signup, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all signups as @signups" do
      Signup.stub(:all) { [mock_signup] }
      get :index
      assigns(:signups).should eq([mock_signup])
    end
  end

  describe "GET show" do
    it "assigns the requested signup as @signup" do
      Signup.stub(:find).with("37") { mock_signup }
      get :show, :id => "37"
      assigns(:signup).should be(mock_signup)
    end
  end

  describe "GET new" do
    it "assigns a new signup as @signup" do
      Signup.stub(:new) { mock_signup }
      get :new
      assigns(:signup).should be(mock_signup)
    end
  end

  describe "GET edit" do
    it "assigns the requested signup as @signup" do
      Signup.stub(:find).with("37") { mock_signup }
      get :edit, :id => "37"
      assigns(:signup).should be(mock_signup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created signup as @signup" do
        Signup.stub(:new).with({'these' => 'params'}) { mock_signup(:save => true) }
        post :create, :signup => {'these' => 'params'}
        assigns(:signup).should be(mock_signup)
      end

      it "redirects to the created signup" do
        Signup.stub(:new) { mock_signup(:save => true) }
        post :create, :signup => {}
        response.should redirect_to(signup_url(mock_signup))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved signup as @signup" do
        Signup.stub(:new).with({'these' => 'params'}) { mock_signup(:save => false) }
        post :create, :signup => {'these' => 'params'}
        assigns(:signup).should be(mock_signup)
      end

      it "re-renders the 'new' template" do
        Signup.stub(:new) { mock_signup(:save => false) }
        post :create, :signup => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested signup" do
        Signup.stub(:find).with("37") { mock_signup }
        mock_signup.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :signup => {'these' => 'params'}
      end

      it "assigns the requested signup as @signup" do
        Signup.stub(:find) { mock_signup(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:signup).should be(mock_signup)
      end

      it "redirects to the signup" do
        Signup.stub(:find) { mock_signup(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(signup_url(mock_signup))
      end
    end

    describe "with invalid params" do
      it "assigns the signup as @signup" do
        Signup.stub(:find) { mock_signup(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:signup).should be(mock_signup)
      end

      it "re-renders the 'edit' template" do
        Signup.stub(:find) { mock_signup(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested signup" do
      Signup.stub(:find).with("37") { mock_signup }
      mock_signup.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the signups list" do
      Signup.stub(:find) { mock_signup }
      delete :destroy, :id => "1"
      response.should redirect_to(signups_url)
    end
  end

end
